providers = ['node']

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve -s dist -l 8080 --config serve.json'

[variables]
NODE_ENV = 'production'
PORT = '8080'
